### ISSUE TITLE
Bug code-server plugin vscode settings

### ISSUE THREAD

**Issue by gjrtimmer** [coder/modules#357] opened 2024-12-02 19:28 UTC
L.S.

I found the following bug. The `settings` variable of the `code-server` module is currently typed as `[map(string).](https://github.com/coder/modules/blob/675c82367a3d53be5f719fca4444fbf5b0ce22ac/code-server/main.tf#L42)` This is a bug, in my opinion, because it does now allow settings with subkeys to be used, which causes a Terraform error. After all, the value is not a string.

```json
settings = {
  "yaml.customTags": [
    "!reference sequence",
    "!vault scalar",
    "inputs sequence"
  ]
}
```

FIX: To allow vscode setting to be set correctly, the type of the variable should be `map(object)`.

Please advice.

**Comment by matifali** [comment] 2024-12-03 06:55
Duplicate of #296

**Comment by matifali** [comment] 2024-12-03 06:56
Hi @gjrtimmer Thanks for highlighting this. Can you please leave your feedback on the existing issue. Also, we are open to contributions if you want to help fix this.
Thanks.

**Closed by matifali** 2024-12-03 06:56 UTC
Labels: docs, help wanted
